### ISSUE TITLE
node-sass should be a development dependency

### ISSUE THREAD

**Issue by adborden** [ca-cwds/react-wood-duck#123]
We're trying to use react-wood-duck in our project but ran into some issues with the `node-sass` dependency. I would expect that the assets are compiled before being packaged, so `node-sass` isn't needed at runtime and should be listed as a development dependency instead.

**Comment by NagaPradeepGajula-osi** [comment]
@adborden this issue is taken care in the PR https://github.com/ca-cwds/react-wood-duck/pull/131 and published with new version 0.1.70. So closing this as its now resolved.
