### ISSUE TITLE
Yarn lockfile out of sync?

### ISSUE THREAD

**Issue by eckdanny-osi** [ca-cwds/react-wood-duck#32]
Just checked out master (d61ff86) and installed deps via `yarn` and found diffs in the lockfile.

Steps to reproduce:

```sh
git pull --ff-only origin master
rm -rf node_modules
yarn install
git diff | wc -l 
   598
```

Dep changes in `package.json` and `yarn.lock` _should_ be in lock-step. Guessing maybe some contribs are using `npm`?)

**Comment by eckdanny-osi** [comment]
Looks like #24, #25, and #27 all change change deps but no deltas in lockfile were committed

😒

**Comment by eckdanny-osi** [comment]
some suggested reading from [yarn blog](https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/) regarding lockfiles

**Comment by edgibbs** [comment]
resolved
