### ISSUE TITLE
Why track dist in version control?

### ISSUE THREAD

**Issue by eckdanny-osi** [ca-cwds/react-wood-duck#8]
Its uncommon to track processed files (e.g.; `dist`) in version control. Is there a reason for doing so?

Asking b/c its _kindofa_ pain to look at PR diffs

**Comment by edgibbs** [comment]
There is one current reason that would need to get resolved and that's hosting the static pages for Storybook on github.

**Comment by edgibbs** [comment]
Starting cleanup in a Pivotal story, should be resolved before the end of Case Management's next sprint.

**Comment by NagaPradeepGajula-osi** [comment]
As the dist is now removed from Github tracking, Can we close this issue?

**Comment by edgibbs** [comment]
So the dist folder is still there, can we remove it completely or empty it out with a .keep file?

**Comment by eckdanny-osi** [comment]
#7 added `dist` to git ignores
#13 removed all `dist` files

Git only tracks files so it wont clean up empty directories for you. Contributors can `rmdir` if its still dangling on your filesystem.

Closing.
