### ISSUE TITLE
To compile Binary assets (fonts, images, etc) to dist use webpacker, css loader 

### ISSUE THREAD

**Issue by Sushmareddy-OSI** [ca-cwds/react-wood-duck#89]
https://github.com/ca-cwds/react-wood-duck/blob/68e1e9c8de73c6cc38bef25db1c2757776102746/webpack.config.js#L1-L14

refer https://github.com/webpack-contrib/css-loader#assets

**Comment by eckdanny-osi** [comment]
+1. I'll have to double-check, but I don't believe binary assets (e.g.; `fonts`) are actually included in the npm package. Ran into this (and TODO_OPEN_ISSUE_FOR_PREPUBLISH_HOOK).

**Comment by NagaPradeepGajula-osi** [comment]
closing this as this was addressed long back in PR https://github.com/ca-cwds/react-wood-duck/pull/111
